### ISSUE TITLE
Add clear guidelines for whether a topic is "too advanced" or should be added/mentioned

### ISSUE THREAD

**Issue by Ilan-Messing** [gamemanual0/gm0#148]
Maybe this already exists idk but for longer term sustainability some guidelines could be established. I just find it common for someone to ask "should xxx programming topic or xxx drivetrain be added" and then the same old discussion ensues. Just a couple of bullet points of guidance could be useful

**Comment by dansman805** [comment]
I feel like one reasonable guideline is "is thing x popularish among either competitive teams or teams overall", *even for bad ideas*. If a generally bad idea gets popular, it should still be at least mentioned as an option, so that it can have its pros/cons reasonably enumerated; swerve is generally a bad idea, and isn't popular, and so isn't covered, especially since it *seems* like a good idea and would likely tempt some teams to use it; h-drive is also generally a bad idea, but is covered, as it's more popular. Another reason it's important  is that some stuff just needs documentation more simply because more people are doing it, and need guidance—writing a dead wheel page would be pretty misguided in velocity vortex, but in ultimate goal makes sense.

So uh tl;dr one of the guidelines should probably be "is it popular?" or something.
