### ISSUE TITLE
Add 20700 to the multi axis arm page

### ISSUE THREAD

**Issue by Seb-Robochoa** [gamemanual0/gm0#273]
![image](https://user-images.githubusercontent.com/70760353/184447022-198b72e7-6489-4e5a-b7a1-ed41b2e66378.png)
maybe add this to the multiaxis arm page along with their reveal? It's a more recent example of a multi axis arm.

**Comment by Eeshwar-Krishnan** [comment]
Most gm0 images are horizontal instead of vertical, and its also a little difficult to see the arm in that image. I think this image from their reveal probably works better
<img width="719" alt="20700-snap" src="https://user-images.githubusercontent.com/32040858/184467531-7edaeed7-83ab-4056-a83e-3e83985a85c1.png">
